### PR TITLE
Fix parsing of video urls

### PR DESCRIPTION
**Pull request by dimio5**
This PR fixes the parsing of video urls, which is currently broken

### CODE REVIEW

**Review by camalot — APPROVED** [review]
Looks good, I will merge it in and get a new build out... thanks! I didn't even realize it was broken 👍

**Comment by dimio5** [comment]
Thanks. I tried to submit another one for adding support for subtitles, but somehow it got merged into this one. Plz, feel free to drop it if you want me to resubmit them.

**Comment by camalot** [comment]
Its fine, it's because the work is in the same branch. I will look at those
changes too. As long as it all works, I'll include it as well.

**Review by camalot — APPROVED** [review]

**Comment by camalot** [comment]
I found a couple little issues after merging it in. I think i have them all fixed now.  It was failing if there were not any subtitles.

**Comment by dimio5** [comment]
Cool, I did not find any videos without subtitles to test it myself. Good catch! And sorry for the indent mess, I used a mix of notepad & vs since I dont have kodi on my main pc. 

If I may ask one question here: how do you publish updates? I tried your repository but it did not work, so I installed manually. Could you please include instructions in the readme?

**Comment by camalot** [comment]
The repository @ https://github.com/camalot/repository.camalot did not
load, or it did not update the plugin?

I didn't kick off the job that updates the repo, guess I should do that...

**Comment by dimio5** [comment]
Well, I select the repo, I select the addon, I select install and nothing happens. No errors in the log too.
Never had this problem with other repos. (i'm using the win10 app)

**Comment by camalot** [comment]
Ahhh, probably because I didn't update the version in the repo. it should be running now to update the repo. 

I forgot that I had to run that. It's one of those things were I never think about it.

**Comment by camalot** [comment]
Ok, it is now also updated in the repo. Thanks for letting me know about that. I would have not even realized it. Since I installed it manually to test it out.

I am going to update the readme with some simple instructions that link to the repo page or to manually install it.

**Comment by dimio5** [comment]
That did not fix it I am afraid. I can see the new version but it does not install: it behaves the same way; it does not show anything and there is no error in the log.

I turned on the debug mode, just in case it helps:
09:21:23.161 T:2100   DEBUG: Previous line repeats 4 times.
09:21:23.161 T:2100   DEBUG: Thread JobWorker 2100 terminating (autodelete)
09:21:23.173 T:7004   DEBUG: Thread JobWorker 7004 terminating (autodelete)
09:21:23.208 T:972   DEBUG: Thread JobWorker 972 terminating (autodelete)
09:21:23.220 T:4220    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://camalot.github.io (easy=21E05038, multi=00000000)
09:21:23.221 T:4220    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://camalot.github.io (easy=0CCEA2C0, multi=00000000)
09:21:23.221 T:4220    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://camalot.github.io (easy=21A8D7B8, multi=00000000)
09:21:23.290 T:9072   DEBUG: Thread JobWorker 9072 terminating (autodelete)
09:21:23.720 T:4220    INFO: XCURL::DllLibCurlGlobal::CheckIdle - Closing session to https://camalot.github.io (easy=0E077538, multi=00000000)
09:21:23.779 T:6736   DEBUG: PERIPHERALS::CPeripherals::GetMappingForDevice - device (2548:1002) mapped to Pulse-Eight CEC Adapter (type = cec)
09:21:55.204 T:4220   DEBUG: Previous line repeats 6 times.
09:21:55.204 T:4220   DEBUG: CWinEventsWin32::WndProcWindow is active
09:21:55.221 T:4220   DEBUG: ------ Window Init (Pointer.xml) ------
09:21:56.147 T:2016   DEBUG: Thread JobWorker start, auto delete: true
09:21:56.151 T:2016    INFO: XCURL::DllLibCurlGlobal::easy_aquire - Created session to https://camalot.github.io
09:21:56.164 T:8360   DEBUG: Thread JobWorker start, auto delete: true
09:21:56.165 T:8360    INFO: XCURL::DllLibCurlGlobal::easy_aquire - Created session to https://camalot.github.io
09:21:56.188 T:8660   DEBUG: Thread JobWorker start, auto delete: true
09:21:56.255 T:8660   DEBUG: Previous line repeats 1 times.
09:21:56.256 T:8660    INFO: XCURL::DllLibCurlGlobal::easy_aquire - Created session to https://camalot.github.io
09:21:56.527 T:2016    INFO: Previous line repeats 1 times.
09:21:56.527 T:2016   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.wwdc/fanart.jpg
09:21:56.532 T:8360   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.twit_api/fanart.jpg
09:21:56.552 T:8660   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.nasa/fanart.jpg
09:21:56.696 T:4092   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.microsoftvirtualacademy/fanart.jpg
09:21:57.275 T:5848   DEBUG: CAESinkDirectSound::Deinitialize: Cleaning up
09:21:58.788 T:6736   DEBUG: PERIPHERALS::CPeripherals::GetMappingForDevice - device (2548:1002) mapped to Pulse-Eight CEC Adapter (type = cec)
09:21:59.683 T:4220   DEBUG: Keyboard: scancode: 0x1c, sym: 0x010f, unicode: 0x000d, modifier: 0x0
09:21:59.724 T:4220   DEBUG: CInputManager::OnKey: enter (0xf065) pressed, action is Select
09:21:59.724 T:4220   DEBUG: ------ Window Init (DialogAddonInfo.xml) ------
09:21:59.724 T:5848    INFO: CActiveAESink::OpenSink - initialize sink
09:21:59.724 T:5848   DEBUG: CActiveAESink::OpenSink - trying to open device DIRECTSOUND:default
09:21:59.728 T:4220   DEBUG: ------ Window Deinit (Pointer.xml) ------
09:21:59.736 T:5848   DEBUG: CAESinkDirectSound::Initialize: Using Window handle: 009105C6
09:21:59.745 T:5848   DEBUG: CAESinkDirectSound::Initialize: secondary buffer created
09:21:59.746 T:5848   DEBUG: CAESinkDirectSound::Initialize: Initializing DirectSound with the following parameters:
09:21:59.746 T:5848   DEBUG:   Audio Device    : 1 - SAMSUNG (AMD High Definition Audio Device)
09:21:59.746 T:5848   DEBUG:   Sample Rate     : 44100
09:21:59.746 T:5848   DEBUG:   Sample Format   : AE_FMT_FLOAT
09:21:59.746 T:5848   DEBUG:   Bits Per Sample : 32
09:21:59.746 T:5848   DEBUG:   Valid Bits/Samp : 32
09:21:59.746 T:5848   DEBUG:   Channel Count   : 2
09:21:59.746 T:5848   DEBUG:   Block Align     : 8
09:21:59.746 T:5848   DEBUG:   Avg. Bytes Sec  : 352800
09:21:59.746 T:5848   DEBUG:   Samples/Block   : 32
09:21:59.746 T:5848   DEBUG:   Format cBSize   : 22
09:21:59.746 T:5848   DEBUG:   Channel Layout  : FL,FR
09:21:59.746 T:5848   DEBUG:   Channel Mask    : 3
09:21:59.746 T:5848   DEBUG:   Frames          : 661
09:21:59.746 T:5848   DEBUG:   Frame Size      : 8
09:21:59.746 T:5848   DEBUG: CActiveAESink::OpenSink - DIRECTSOUND Initialized:
09:21:59.746 T:5848   DEBUG:   Output Device : default
09:21:59.746 T:5848   DEBUG:   Sample Rate   : 44100
09:21:59.746 T:5848   DEBUG:   Sample Format : AE_FMT_FLOAT
09:21:59.747 T:5848   DEBUG:   Channel Count : 2
09:21:59.747 T:5848   DEBUG:   Channel Layout: FL,FR
09:21:59.747 T:5848   DEBUG:   Frames        : 661
09:21:59.747 T:5848   DEBUG:   Frame Size    : 8
09:21:59.776 T:5848   DEBUG: CAESinkDirectSound::CheckPlayStatus: Resuming Playback
09:22:00.603 T:4220   DEBUG: Keyboard: scancode: 0x1c, sym: 0x010f, unicode: 0x000d, modifier: 0x0
09:22:00.644 T:4220   DEBUG: CInputManager::OnKey: enter (0xf065) pressed, action is Select
09:22:00.648 T:4220   DEBUG: CAddonInstaller: installing 'plugin.video.microsoft.channel9' version '2.0.63.28717' from repository 'repository.camalot'
09:22:00.654 T:4220   DEBUG: Keyboard: scancode: 0x1c, sym: 0x010f, unicode: 0x0000, modifier: 0x0
09:22:00.773 T:860   DEBUG: CMMNotificationClient::OnPropertyValueChanged: Changed device property of {0.0.0.00000000}.{6fdedaa7-1498-432d-a721-ed8842f3e072} is {9855c4cd-df8c-449c-a181-8191b68bd06c}#0
09:22:00.939 T:4220   DEBUG: ------ Window Deinit (DialogAddonInfo.xml) ------
09:22:00.953 T:4220   DEBUG: Keyboard: scancode: 0x1c, sym: 0x010f, unicode: 0x0000, modifier: 0x0
09:22:02.880 T:4220   DEBUG: Keyboard: scancode: 0x38, sym: 0x0134, unicode: 0x0000, modifier: 0x100
09:22:02.880 T:4220   DEBUG: CInputManager::OnKey: alt-leftalt (0x4f0d4) pressed, action is
09:22:02.923 T:4220   DEBUG: CWinEventsWin32::WndProcWindow is active
09:22:02.924 T:4220   DEBUG: CWinEventsWin32::WndProc: Focus switched to process C:\Windows\explorer.exe
09:22:03.789 T:6736   DEBUG: PERIPHERALS::CPeripherals::GetMappingForDevice - device (2548:1002) mapped to Pulse-Eight CEC Adapter (type = cec)
09:22:04.657 T:4220   DEBUG: ------ Window Init (Pointer.xml) ------
09:22:07.550 T:4220   DEBUG: CWinEventsWin32::WndProcWindow is active
09:22:07.803 T:4092   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.image.kochandi/fanart.jpg
09:22:07.903 T:8660   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.image.kodur/fanart.jpg
09:22:07.999 T:8360   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.microsoftvirtualacademy/fanart.jpg
09:22:08.055 T:4092   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.nasa/fanart.jpg
09:22:08.125 T:2016   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.twit_api/fanart.jpg
09:22:08.151 T:8660   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.twit_api/icon.png
09:22:08.251 T:8360   DEBUG: CTextureCacheJob::GetImageHash - unable to stat url https://camalot.github.io/repository.camalot/plugin.video.wwdc/fanart.jpg
09:22:08.520 T:4220   DEBUG: Keyboard: scancode: 0x38, sym: 0x0134, unicode: 0x0000, modifier: 0x100
09:22:08.520 T:4220   DEBUG: CInputManager::OnKey: alt-long-leftalt (0x104f0d4) pressed, action is
09:22:08.620 T:4220   DEBUG: CWinEventsWin32::WndProcWindow is active
09:22:08.621 T:4220   DEBUG: CWinEventsWin32::WndProc: Focus switched to process C:\Windows\explorer.exe
09:22:08.790 T:6736   DEBUG: PERIPHERALS::CPeripherals::GetMappingForDevice - device (2548:1002) mapped to Pulse-Eight CEC Adapter (type = cec)

**Comment by camalot** [comment]
Hmmm interesting. I am able to reproduce that. I installed an older version manually, tried to update but it just doesn't update. 

I will create an issue and look into it.

**Pull request merged**
